name: Build Apk

on:
  push:
    tags:
      - 'v*'  # 触发条件：当推送标签以 'v' 开头时
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-22.04  # 使用 Ubuntu 运行环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      # with:
          # submodules: true
          # repository: catpuppyapp/PuppyGit
          # fetch-depth: 1
          # ref: main
          # path: PuppyGit  # if set, must use `$GITHUB_WORKSPACE/PuppyGit` to access the dir, else can simple use `$GITHUB_WORKSPACE`


      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'  # 设置 JDK 版本
          distribution: 'temurin'  # 指定 JDK 发行版（例如 'adopt', 'zulu', 'temurin', 'oracle' 等）
          cache: 'gradle' # 开启 gradle 缓存，加速后续构建

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            curl \
            make \
            tar \
            unzip \
            git

      # code_forge requires rustup
      - name: install rust-toolchain
        uses: dtolnay/rust-toolchain@stable
      - run: cargo --version

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: ${{ github.workspace }}/haha_note_src/pubspec.yaml
          cache: true # 开启 flutter 缓存，下次可能就不会重新下载了，而是复用已下载的sdk
      - run: flutter --version

      - name: Build Release APK
        working-directory: haha_note_src
        run: |
          cd build_script
          chmod +x bapk_build_apk.sh
          ./bapk_build_apk.sh

      - name: Upload Release APK
        uses: actions/upload-artifact@v7
        with:
          name: app-release-unsigned.apk
          path: ${{ github.workspace }}/haha_note_src/build/app/outputs/flutter-apk
          retention-days: 15

