name: Build Windows Bundle

on:
  push:
    tags:
      - 'v*'  # 触发条件：当推送标签以 'v' 开头时
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Enable Git longpaths
        run: git config --system core.longpaths true

      # code_forge requires rustup
      - name: install rust-toolchain
        uses: dtolnay/rust-toolchain@stable
      - run: cargo --version

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: ${{ github.workspace }}/haha_note_src/pubspec.yaml
          cache: true # 开启 flutter 缓存，下次可能就不会重新下载了，而是复用已下载的sdk
      - run: flutter --version

      - name: Build
        env:
          # 注入编译器标志，静默弃用警告
          # for build cargokit, that the flutter rust bridge dependency it, 
          # cargokit is out-of-dated, by the way
          CXXFLAGS: "/D_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS"
        working-directory: haha_note_src
        # if use cd change dir: 
        # should use ${{ github.workspace }} in yaml, it can be replace path before execute
        # if use $GITHUB_WORKSPACE, in powershell maybe must write as $env:GITHUB_WORKSPACE
        # cd ${{ github.workspace }}\haha_note_src\build_script
        run: |
          cd build_script
          .\bwo_build_windows_only.ps1

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: windows_bundle
          path: ${{ github.workspace }}/haha_note_src/build/windows/x64/runner/*.zip
          retention-days: 15

